services:
  backend:
    image: aro2304/hemoflow-backend:latest
    container_name: blood-donation-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend-nw
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: aro2304/hemoflow-frontend:latest
    container_name: blood-donation-ui
    restart: unless-stopped
    networks:
      - frontend-nw
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: blood-donation-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    networks:
      - backend-nw
    volumes:
      - db-data:/var/lib/mysql
      - ./setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_ROOT_PASS"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  frontend-nw:
    driver: bridge
  backend-nw:
    driver: bridge

volumes:
  db-data: